### ISSUE TITLE
Crashs sometimes

### ISSUE THREAD

**Issue by bernal01** [Bara/TroubleinTerroristTown#172] opened 2017-09-02 21:30 UTC
Sometimes the server crashes when the round log is being generated.
https://crash.limetech.org/nw5gsc5krpsd

**Comment by popey456963** [comment] 2017-09-05 22:57
We've found a reproducible way to get this exact crash ([example](https://crash.limetech.org/2xtr245vxg3g)).

**Steps**:

1. Grab a friend, this requires at least two people.
2. Go on a map that has a prop or traitor trap that can kill multiple people via physics crushing (we use [ttt_closequarters](https://gamebanana.com/maps/195235).
3. Wait for round to start, traitor spawns a fakebody, we think it also works with normal bodies but we haven't tried.
4. Crush the fakebody into the alive player, server will crash.

[gif](https://puu.sh/xsuG9/33b05ce295.gif)

**Comment by popey456963** [comment] 2017-09-06 17:01
You can also get it into a scenario like:

![](https://i.imgur.com/snRN6It.png)

And if you kill the person the prop will crash the server.  It appears to be something about the interaction with some prop & a body that dies.

**Comment by whocodes** [comment] 2017-09-07 00:54
Possibly an issue with ragdoll collision? Could be an issue with the game itself.

**Comment by popey456963** [comment] 2017-11-13 23:06
Myself and the @good-live seem to be getting this crash too a bit, signature has changed a bit in time.

https://crash.limetech.org/stats/299d4f49fd2b9d73f89d2f43d2898cbb262516f5d2a6940538112019393954f182d7803f2722e0a2

**Comment by Bara** [comment] 2017-11-28 05:14
No crashes since 13th or crashes with other reasons?

**Comment by popey456963** [comment] 2017-11-28 22:15
@Bara We've still got crashes for bodies dying within each other.

**Comment by popey456963** [comment] 2017-11-28 22:16
Here are a couple from today:

- https://crash.limetech.org/BUILGNINN3TY
- https://crash.limetech.org/6CJLT2QNDP4Z

Yesterday we had one:

- https://crash.limetech.org/LHEWFPRI5QLN

Three days ago:

- https://crash.limetech.org/OCW6DDWXYGXP

**Comment by Bara** [comment] 2017-12-03 13:37
And without grabbermod? @popey456963

**Comment by popey456963** [comment] 2017-12-04 01:14
@Bara Never tried it without grabbermod, one of the best parts of TTT :)

All of those last 4 instances I posted were linked to multiple people dying within each other, none of them included using the grabbermod on corpses.  I'm not sure whether just having the mod installed would cause such crashes to happen, even if it isn't used.

**Comment by popey456963** [comment] 2018-01-04 15:38
Setting collision group to `COLLISION_GROUP_DEBRIS_TRIGGER` (2) on collision seems to avoid the crashes without any weird side effects.

**Comment by Bara** [comment] 2018-01-04 15:42
Of ragdolls?

**Comment by popey456963** [comment] 2018-01-04 17:44
Everyone, players and rag dolls. I tried just rag dolls at first, but I didn't seem to be able to change the collision type before the crash occurred.

**Comment by Bara** [comment] 2018-01-04 17:46
Do you've time to create a pull request?

**Comment by popey456963** [comment] 2018-01-04 17:50
Will have to ask the friend I borrowed the code from. 🙂

**Comment by popey456963** [comment] 2018-01-04 21:03
I was premature on the celebration, although I hadn't crashed in a day and a half, that seemed to be mostly down to luck.  Just had a crash with the same signature:

    https://crash.limetech.org/BSTKZVJWCUSP

**Comment by NicronS** [comment] 2018-01-13 06:16
@Bara I'm going to work on this. We have the same issue in HeLLsGamers, except ours has an issue when players stand inside each-other and die at the same time the server crashes with a physics error [crash](https://crash.limetech.org/kkrij3d2ajii)

**Comment by popey456963** [comment] 2018-01-13 13:20
@NicronS, if it helps, we've found the crash originates around the `m_bSpottedByMask` property for some reason. At least, our latest crash with that reason.

**Comment by popey456963** [comment] 2018-01-13 13:20
@NicronS, if it helps, we've found the crash originates around the `m_bSpottedByMask` property for some reason. At least, our latest crash with that reason.

**Comment by Bara** [comment] 2018-02-11 00:48
So btw. @popey456963 we don't use m_bSpottedByMask

**Comment by popey456963** [comment] 2018-02-11 01:39
@Bara Well, isn't that awkward?  I imagine it may be something you're using that utilises that variable as opposed to you using it directly, it seems pretty specific.

I'll go ask the awesome person who found that out for me to go slightly higher in the stack trace to see if we can find out what in TTT is actually causing the crash.  Afraid I'm not 100% how he did it :)

**Comment by Bara** [comment] 2018-02-11 01:58
So i searched for "spot" (whole scripting folder + sub) with 2 hits, but there are unrelated.

**Comment by popey456963** [comment] 2018-07-18 21:55
Woah woah, don't close this issue?  Any chance of getting it reopened @Bara?

It's still a problem, just a particuarly challenging one.

**Comment by Bara** [comment] 2018-07-18 21:57
That was a bot @popey456963 . I play a bit with no-reponse and autolock.

**Comment by millerze** [comment] 2018-09-30 01:17
We crashed 2-5 times a day to this.  We also noticed it happens a lot on clue when people are stacked in a closet.  It's pretty brutal bug.

**Comment by good-live** [comment] 2018-09-30 08:11
Can you provide some error logs or a accelerator log? Maybe it's a different problem. @millerze

**Comment by millerze** [comment] 2018-09-30 13:06
I'm new to the limetech/accelerator thing.  From what I can see there is 3 different signatures we're crashing from.  
https://crash.limetech.org/ckvaewv5d2kr
https://crash.limetech.org/73mvpqykczzx
https://crash.limetech.org/n3qqfdgznrhy

**Comment by millerze** [comment] 2018-10-03 04:05
The most common is https://crash.limetech.org/jqhvv27ii4qc
vphysics.so + 0x10d1b5
50% of our crashes share this signature.  I'm pretty sure that me dying in the vents in ttt_dolls as another person was passing me crashed it.  I'm really convinced it has to do with ragdoll collision as commented above.

**Comment by popey456963** [comment] 2018-10-03 20:20
Same signature as my recent ones, seems like the same bug.

**Comment by millerze** [comment] 2018-10-04 01:46
The code that deals with collision of ragdolls, this that you experimented with @popey456963 right?
From ttt.sp:

SetEntProp(iEntity, Prop_Data, "m_CollisionGroup", 5);
TeleportEntity(iEntity, origin, angles, NULL_VECTOR);
SetEntProp(iEntity, Prop_Data, "m_CollisionGroup", 2);

Anyone know why @Bara sets the collusion group to COLLISION_GROUP_DEBRIS_TRIGGER, then teleports it, then changed the collusion group again to COLLISION_GROUP_PLAYER?

Why not COLLISION_GROUP_NONE?  I haven't really haven't had to deal with collision much.

**Comment by Bara** [comment] 2018-10-04 09:10
[COLLISION_GROUP_DEBRIS_TRIGGER exist since beginning.](https://github.com/Bara/TroubleinTerroristTown/blob/4036bda34f9bbb9b4b68eb359075ddb6eea3f72c/addons/sourcemod/scripting/ttt.sp#L793)
[COLLISION_GROUP_PLAYER was added to fix a glitch/collision bug(?)](https://github.com/Bara/TroubleinTerroristTown/commit/e14369a5c735629b968deefa009b56c6f92ef3e0)

But you can compile TTT for yourself and change it to what you think. If you found a fix, let us know.

**Comment by millerze** [comment] 2018-10-04 13:01
Will do @Bara!

**Comment by Bara** [comment] 2018-10-26 22:37
@millerze Any updates here?

**Comment by Squallkins** [comment] 2018-10-29 22:44
Crashes still happen after [https://github.com/Bara/TroubleinTerroristTown/commit/80010439d78696db067c61b78a70cc3257bea37e](commit 8001043) changes.

https://crash.limetech.org/l6xuvqsw73qg

**Comment by Bara** [comment] 2018-10-30 10:51
@Squallkins Do you ideally found a way to reproduce this crash?
I tried several way to get a crash but without success.
Like: https://www.youtube.com/watch?v=RnBDFZzld54 or https://www.youtube.com/watch?v=N4ZdLYPFYwY (with this way a got a crash before the change)

**Comment by Squallkins** [comment] 2018-10-30 21:48
No unfortunately.  We haven't been able to reproduce it on demand.

**Comment by Bara** [comment] 2018-10-31 01:12
Could you try this commit? https://github.com/Bara/TroubleinTerroristTown/commit/12c1e1365ca473d843085119c1e2fadc4c639879

**Comment by popey456963** [comment] 2018-10-31 22:09
We couldn't get it to crash in a couple of hours of testing.  It seems like this commit has fixed it! :)

**Comment by Squallkins** [comment] 2018-10-31 22:13
We had a crash with that commit : https://crash.limetech.org/pwe764e5xqb4

**Comment by popey456963** [comment] 2018-11-01 18:02
It might be there are several paths leading to the same stack trace.  We were also unable to crash it today.

**Closed** 2018-11-09 23:18 UTC
Labels: bug, feedback, help wanted
