### ISSUE TITLE
Revive still don't work

### ISSUE THREAD

**Issue by Raku17** [Bara/TroubleinTerroristTown#443] opened 2019-10-29 18:45 UTC
- Version of MetaMod  (meta version)
Metamod:Source version 1.10.7-dev

- Version of SourceMod (sm version)
SourceMod Version: 1.10.0.6453

- List of your extensions (sm exts list)

[SM] Displaying 13 extensions:
[01] Automatic Updater (1.10.0.6453): Updates SourceMod gamedata files
[02] Webternet (1.10.0.6453): Extension for interacting with URLs
[03] CS Tools (1.10.0.6453): CS extended functionality
[04] BinTools (1.10.0.6453): Low-level C/C++ Calling API
[05] SDK Tools (1.10.0.6453): Source SDK Tools
[06] Top Menus (1.10.0.6453): Creates sorted nested menus
[07] Regex (1.10.0.6453): Provides regex natives for plugins
[08] SDK Hooks (1.10.0.6453): Source SDK Hooks
[09] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
[10] Client Preferences (1.10.0.6453): Saves client preference settings
[11] SQLite (1.10.0.6453): SQLite Driver
[12] <OPTIONAL> file "vphysics.ext.so": /home/container/csgo/addons/sourcemod/extensions/vphysics.ext.so: cannot open shared object file: No such file or directory
[13] PTaH (1.1.1): Additional CS:GO Hooks and Natives

- Version of TTT (sm_tttversion)
TTT Version: 3.2137

- List of your plugins (sm plugins list)
[SM] Listing 76 plugins:
01 "Basic Commands" (1.10.0.6453) by AlliedModders LLC
02 "Block messages" (1.0.0) by Bara
03 "Admin Help" (1.10.0.6453) by AlliedModders LLC
04 "Basic Info Triggers" (1.10.0.6453) by AlliedModders LLC
05 "SM Parachute" (2.5) by SWAT_88
06 "Basic Ban Commands" (1.10.0.6453) by AlliedModders LLC
07 "Trouble in Terrorist Town - Hide Radar" (3.2137) by TTT-Contributors
08 "Trouble in Terrorist Town - Dna Scanner" (3.2137) by TTT-Contributors
09 "Trouble in Terrorist Town - Spec Menu" (3.2137) by TTT-Contributors
10 "Trouble in Terrorist Town - Fake Name" (3.2137) by TTT-Contributors
11 "Trouble in Terrorist Town - Nightvision" (3.2137) by TTT-Contributors
12 "Trouble in Terrorist Town - Blackout" (3.2137) by TTT-Contributors
13 "Trouble in Terrorist Town - Glow" (3.2137) by TTT-Contributors
14 "Trouble in Terrorist Town - Knockout" (3.2137) by TTT-Contributors
15 "Trouble in Terrorist Town - Sprint" (3.2137) by TTT-Contributors
16 "Trouble in Terrorist Town - Items: Revive" (3.2137) by TTT-Contributors
17 "Trouble in Terrorist Town" (3.2137) by TTT-Contributors
18 "Trouble in Terrorist Town - Traitor Doors" (3.2137) by TTT-Contributors
19 "Trouble in Terrorist Town - Shop Discounts" (3.2137) by TTT-Contributors
20 "Trouble in Terrorist Town - Revolver" (3.2137) by TTT-Contributors
21 "Trouble in Terrorist Town - Poison Smoke" (3.2137) by TTT-Contributors
22 "Trouble in Terrorist Town - Turret" (3.2137) by TTT-Contributors & bbs.93x.net
23 "Trouble in Terrorist Town - Round End Sounds" (3.2137) by TTT-Contributors
24 "Trouble in Terrorist Town - Items: Ice Knife" (3.2137) by TTT-Contributors
25 "Trouble in Terrorist Town - Grabber Mod" (3.2137) by TTT-Contributors
26 "Trouble in Terrorist Town - Silent AWP" (3.2137) by TTT-Contributors
27 "Trouble in Terrorist Town - Overlays" (3.2137) by TTT-Contributors
28 "Trouble in Terrorist Town - Tracer" (3.2137) by bbs.93x.net & zipcore
29 "Trouble in Terrorist Town - SQL Manager" (3.2137) by TTT-Contributors
30 "Trouble in Terrorist Town - Items: Weapons" (3.2137) by TTT-Contributors
31 "Trouble in Terrorist Town - TA-Grenade" (3.2137) by TTT-Contributors
32 "Trouble in Terrorist Town - Items: ID" (3.2137) by TTT-Contributors
33 "Trouble in Terrorist Town - Items: Decoy Teleporter" (3.2137) by TTT-Contributors
34 "Trouble in Terrorist Town - Buy Roles" (3.2137) by TTT-Contributors
35 "Trouble in Terrorist Town - Crash Catcher" (3.2137) by TTT-Contributors
36 "Trouble in Terrorist Town - Decoy Body" (3.2137) by TTT-Contributors
37 "Trouble in Terrorist Town - Hurtshot" (3.2137) by TTT-Contributors
38 "Trouble in Terrorist Town - Teleporter" (3.2137) by TTT-Contributors
39 "Trouble in Terrorist Town - Items: Fake Body" (3.2137) by TTT-Contributors
40 "Trouble in Terrorist Town - Hud" (3.2137) by TTT-Contributors
41 "Trouble in Terrorist Town - Health/Hurt Stations" (3.2137) by TTT-Contributors
42 "Trouble in Terrorist Town - Traitor Buttons" (3.2137) by TTT-Contributors
43 "Trouble in Terrorist Town - Items: Healthshot" (3.2137) by TTT-Contributors
44 "Trouble in Terrorist Town - Tripmines" (3.2137) by TTT-Contributors
45 "Trouble in Terrorist Town - Drop Weapons" (3.2137) by TTT-Contributors
46 "Trouble in Terrorist Town - Icons" (3.2137) by TTT-Contributors
47 "Trouble in Terrorist Town - Items: Wallhack" (3.2137) by TTT-Contributors
48 "Trouble in Terrorist Town - Items: Martydom" (3.2137) by TTT-Contributors
49 "Trouble in Terrorist Town - C4 & Jihad" (3.2137) by TTT-Contributors
50 "Trouble in Terrorist Town - Radar" (3.2137) by TTT-Contributors
51 "Trouble in Terrorist Town - Items: Random Teleporter" (3.2137) by TTT-Contributors
52 "Trouble in Terrorist Town - Models" (3.2137) by TTT-Contributors
53 "Trouble in Terrorist Town - Shop" (3.2137) by TTT-Contributors
54 "Trouble in Terrorist Town - Exojump" (3.2137) by TTT-Contributors
55 "Trouble in Terrorist Town - Items: Taser" (3.2137) by TTT-Contributors
56 "Trouble in Terrorist Town - Bullets (Fire, Freeze, Poison)" (3.2137) by TTT-Contributors
57 "Trouble in Terrorist Town - Radio" (3.2137) by TTT-Contributors
58 "Trouble in Terrorist Town - Items: Missiles" (good_live) by TTT-Contributors
59 "Trouble in Terrorist Town - Talk Override" (3.2137) by TTT-Contributors
60 "CS:GO Turret Core" (1.0) by Tast - SDC Edited by Kento & e54385991
61 "sbp.smx"
62 "Fun Votes" (1.10.0.6453) by AlliedModders LLC
63 "Reserved Slots" (1.10.0.6453) by AlliedModders LLC
64 "Admin File Reader" (1.10.0.6453) by AlliedModders LLC
65 "No Weapon Fix" (3.2) by .#Zipcore
66 "Basic Comm Control" (1.10.0.6453) by AlliedModders LLC
67 "Player Commands" (1.10.0.6453) by AlliedModders LLC
68 "Anti-Flood" (1.10.0.6453) by AlliedModders LLC
69 "Fun Commands" (1.10.0.6453) by AlliedModders LLC
70 "Nextmap" (1.10.0.6453) by AlliedModders LLC
71 "Sound Commands" (1.10.0.6453) by AlliedModders LLC
72 "Basic Votes" (1.10.0.6453) by AlliedModders LLC
73 "Basic Chat" (1.10.0.6453) by AlliedModders LLC
74 "Client Preferences" (1.10.0.6453) by AlliedModders LLC
75 "Tripmines 2016 Update" (1.0 ( will be never updated :) )) by 404, Bara
76 "Admin Menu" (1.10.0.6453) by AlliedModders LLC

- TTT related error logs - You can find the logs under: addons/sourcemod/logs/error_*.log
no logs here

- Steps to reproduce this issue
same as before if you can look to before issue, revive dont work
i've created new server, because you're fix didnt worked for me, but it still dont  work

btw. i have more issues, you want them in one post or every issue - 1 post?
i really love your work and i want to make you're plugin without issues to be perfect!

**Comment by Bara** [comment] 2019-10-31 19:12
I couldn't reproduce it with @jnatalejr with the latest source version (comparible with [this tree](https://github.com/Bara/TroubleinTerroristTown/tree/b058da83954dc5fd79698fc78a7b1d97a50f9387) or build 2142).

**Comment by Bara** [comment] 2019-11-08 21:02
I closed it: no feedback.

**Closed** 2019-11-08 21:01 UTC
Labels: feedback, help wanted
