### ISSUE TITLE
Some players can`t check dead body

### ISSUE THREAD

**Issue by rsgua** [Bara/TroubleinTerroristTown#275] opened 2018-01-04 15:14 UTC
Build id: 1475
Last sm and mm
What erros i have:
L 01/04/2018 - 18:08:52: [SM] Blaming: ttt/ttt_models.smx
L 01/04/2018 - 18:08:52: [SM] Call stack trace:
L 01/04/2018 - 18:08:52: [SM]   [0] DirExists
L 01/04/2018 - 18:08:52: [SM]   [1] Line 274, addons/sourcemod/scripting/ttt/ttt_models.sp::SetModel
L 01/04/2018 - 18:08:52: [SM]   [2] Line 207, addons/sourcemod/scripting/ttt/ttt_models.sp::TTT_OnClientGetRole
L 01/04/2018 - 18:08:52: [SM]   [4] Call_Finish
L 01/04/2018 - 18:08:52: [SM]   [5] Line 1285, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize
L 01/04/2018 - 18:08:52: [SM]   [6] Line 1002, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection
L 01/04/2018 - 18:08:52: [SM] Exception reported: Invalid path. An empty path string is not valid, use "." to refer to the current working directory.
L 01/04/2018 - 18:08:52: [SM] Blaming: ttt/ttt_models.smx
L 01/04/2018 - 18:08:52: [SM] Call stack trace:
L 01/04/2018 - 18:08:52: [SM]   [0] DirExists
L 01/04/2018 - 18:08:52: [SM]   [1] Line 274, addons/sourcemod/scripting/ttt/ttt_models.sp::SetModel
L 01/04/2018 - 18:08:52: [SM]   [2] Line 207, addons/sourcemod/scripting/ttt/ttt_models.sp::TTT_OnClientGetRole
L 01/04/2018 - 18:08:52: [SM]   [4] Call_Finish
L 01/04/2018 - 18:08:52: [SM]   [5] Line 1285, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize
L 01/04/2018 - 18:08:52: [SM]   [6] Line 1002, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection

**Comment by Bara** [comment] 2018-01-04 15:48
I've pushed a fix that should fix your issue.

**Comment by Bara** [comment] 2018-01-09 00:02
I can't reproduce this error/bug, your config should be wrong. And the models you sended me are incomplete.

**Closed by Bara** 2018-01-09 00:02 UTC
